Clean up maintscripts
- use /bin/sh instead of /bin/bash
- move #DEBHELPER# to end of script, and remove duplicate #DEBHELPER#
- merge all unused subcommands
- inspired from dh_make templates

diff --git a/debian/shinken-common.postinst b/debian/shinken-common.postinst
--- a/debian/shinken-common.postinst
+++ b/debian/shinken-common.postinst
@@ -1,104 +1,92 @@
-#!/bin/bash
-#DEBHELPER#
+#!/bin/sh
+# postinst script for shinken-common
+#
+# see: dh_installdeb(1)
 
 set -e
 
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
 case "$1" in
-  configure)
-    # Configure this package.  If the package must prompt the user for
-    # information, do it here.
-    :
+    configure)
+        ## Gets some innocent playground
+        TMP=$(mktemp -d)
+        chown root:root $TMP
 
-    ## Gets some innocent playground
-    TMP=$(mktemp -d)
-    chown root:root $TMP
+        ## Adds shinken group
+        chgrp shinken $TMP 2>/dev/null ||
+          addgroup --system shinken
 
-    ## Adds shinken group
-    chgrp shinken $TMP 2>/dev/null ||
-      addgroup --system shinken
+        ## Adds nagios group
+        chgrp nagios $TMP 2>/dev/null ||
+          addgroup --system nagios
 
-    ## Adds nagios group
-    chgrp nagios $TMP 2>/dev/null ||
-      addgroup --system nagios
+        ## Ensure /var/lib/shinken is ready
+        mkdir -p /var/lib/shinken
+        chown -R shinken:shinken /var/lib/shinken
 
-    ## Ensure /var/lib/shinken is ready
-    mkdir -p /var/lib/shinken
-    chown -R shinken:shinken /var/lib/shinken
+        ## Add shinken to nagios group
+        id -Gn shinken |grep -E '(^|[[:blank:]])nagios($|[[:blank:]])' >/dev/null ||
+          usermod -a -G nagios shinken
 
-    ## Add shinken to nagios group
-    id -Gn shinken |grep -E '(^|[[:blank:]])nagios($|[[:blank:]])' >/dev/null ||
-      usermod -a -G nagios shinken
+        ## No need anymore temporary vars
+        rm -rf $TMP
+        unset TMP
 
-    ## No need anymore temporary vars
-    rm -rf $TMP
-    unset TMP
+        ## Ensure /var/run/shinken is ready
+        mkdir -p /var/run/shinken
+        chown -R shinken:shinken /var/run/shinken
 
-    ## Ensure /var/run/shinken is ready
-    mkdir -p /var/run/shinken
-    chown -R shinken:shinken /var/run/shinken
+        ## Ensure /var/log/shinken is ready
+        mkdir -p /var/log/shinken
+        chown -R shinken:shinken /var/log/shinken
 
-    ## Ensure /var/log/shinken is ready
-    mkdir -p /var/log/shinken
-    chown -R shinken:shinken /var/log/shinken
+        ## Checks rights
+        dpkg-statoverride --remove /var/run/shinken/ >/dev/null 2>&1 || true
+        dpkg-statoverride --update --add shinken shinken 02750 /var/run/shinken/ >/dev/null 2>&1 || true
+        dpkg-statoverride --remove /var/log/shinken/ >/dev/null 2>&1 || true
+        dpkg-statoverride --update --add shinken shinken 02750 /var/log/shinken/ >/dev/null 2>&1 || true
+        dpkg-statoverride --remove /var/lib/shinken/ >/dev/null 2>&1 || true
+        dpkg-statoverride --update --add shinken shinken 02750 /var/lib/shinken/ >/dev/null 2>&1 || true
 
-    ## Checks rights
-    dpkg-statoverride --remove /var/run/shinken/ >/dev/null 2>&1 || true
-    dpkg-statoverride --update --add shinken shinken 02750 /var/run/shinken/ >/dev/null 2>&1 || true
-    dpkg-statoverride --remove /var/log/shinken/ >/dev/null 2>&1 || true
-    dpkg-statoverride --update --add shinken shinken 02750 /var/log/shinken/ >/dev/null 2>&1 || true
-    dpkg-statoverride --remove /var/lib/shinken/ >/dev/null 2>&1 || true
-    dpkg-statoverride --update --add shinken shinken 02750 /var/lib/shinken/ >/dev/null 2>&1 || true
+        # We don't we the shinken script
+        # TODO: find a better solution
+        # Maybe move the shinken script in an other folder ?
+        update-rc.d -f shinken defaults > /dev/null
+        update-rc.d -f shinken remove > /dev/null
 
-    # We don't we the shinken script
-    # TODO: find a better solution
-    # Maybe move the shinken script in an other folder ?
-    update-rc.d -f shinken defaults > /dev/null
-    update-rc.d -f shinken remove > /dev/null
-
-    ## Ensure shinken starts automatically
-    update-rc.d -f shinken-arbiter defaults > /dev/null
-    update-rc.d -f shinken-scheduler defaults > /dev/null
-    update-rc.d -f shinken-poller defaults > /dev/null
-    update-rc.d -f shinken-broker defaults > /dev/null
-    update-rc.d -f shinken-reactionner defaults > /dev/null
-    update-rc.d -f shinken-receiver defaults > /dev/null
-
+        ## Ensure shinken starts automatically
+        update-rc.d -f shinken-arbiter defaults > /dev/null
+        update-rc.d -f shinken-scheduler defaults > /dev/null
+        update-rc.d -f shinken-poller defaults > /dev/null
+        update-rc.d -f shinken-broker defaults > /dev/null
+        update-rc.d -f shinken-reactionner defaults > /dev/null
+        update-rc.d -f shinken-receiver defaults > /dev/null
     ;;
-  abort-upgrade)
-    # Back out of an attempt to upgrade this package FROM THIS VERSION
-    # to version $2.  Undo the effects of "prerm upgrade $2".
-    :
 
+    abort-upgrade|abort-remove|abort-deconfigure)
     ;;
-  abort-remove)
-    if test "$2" != in-favour; then
-      echo "$0: undocumented call to \`postinst $*'" 1>&2
-      exit 0
-    fi
-    # Back out of an attempt to remove this package, which was due to
-    # a conflict with package $3 (version $4).  Undo the effects of
-    # "prerm remove in-favour $3 $4".
-    :
 
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
     ;;
-  abort-deconfigure)
-    if test "$2" != in-favour -o "$5" != removing; then
-      echo "$0: undocumented call to \`postinst $*'" 1>&2
-      exit 0
-    fi
-    # Back out of an attempt to deconfigure this package, which was
-    # due to package $6 (version $7) which we depend on being removed
-    # to make way for package $3 (version $4).  Undo the effects of
-    # "prerm deconfigure in-favour $3 $4 removing $6 $7".
-    :
-
-    ;;
-  *) echo "$0: didn't understand being called with \`$1'" 1>&2
-     exit 0;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
+
 #DEBHELPER#
 
 exit 0
diff --git a/debian/shinken-common.preinst b/debian/shinken-common.preinst
--- a/debian/shinken-common.preinst
+++ b/debian/shinken-common.preinst
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/bin/sh
 # preinst script for shinken-common
 #
 # see: dh_installdeb(1)
@@ -10,24 +10,24 @@ set -e
 #        * <new-preinst> `install' <old-version>
 #        * <new-preinst> `upgrade' <old-version>
 #        * <old-preinst> `abort-upgrade' <new-version>
-#
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 
 case "$1" in
     install|upgrade)
-    if id shinken >/dev/null 2>&1 ; then
-        # We have a shinken user.
-        if [ `id shinken -g -n` != "shinken" ] ; then
-            groupadd --system shinken || true
-            #this can fail sometimes (i.e. with LDAP) so ignore it
-            usermod -g shinken shinken || true
+        if id shinken >/dev/null 2>&1 ; then
+            # We have a shinken user.
+            if [ `id shinken -g -n` != "shinken" ] ; then
+                groupadd --system shinken || true
+                #this can fail sometimes (i.e. with LDAP) so ignore it
+                usermod -g shinken shinken || true
+            fi
+        else
+            useradd --system --home-dir /var/lib/shinken shinken || true
         fi
-    else
-        useradd --system --home-dir /var/lib/shinken shinken || true
-    fi
     ;;
+
     abort-upgrade)
     ;;
 
diff --git a/debian/shinken.postinst b/debian/shinken.postinst
--- a/debian/shinken.postinst
+++ b/debian/shinken.postinst
@@ -1,54 +1,43 @@
 #!/bin/bash
-#DEBHELPER#
+# postinst script for shinken
+#
+# see: dh_installdeb(1)
 
 set -e
 
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
 case "$1" in
-  configure)
-
-    # Update-rc
-    all_daemons='arbiter scheduler poller broker reactionner receiver'
-    for daemon_ in $all_daemons; do
-        update-rc.d -f shinken-$daemon_ defaults > /dev/null
-    done
-
+    configure)
+        all_daemons='arbiter scheduler poller broker reactionner receiver'
+        for daemon_ in $all_daemons; do
+            update-rc.d -f shinken-$daemon_ defaults > /dev/null
+        done
     ;;
-  abort-upgrade)
-    # Back out of an attempt to upgrade this package FROM THIS VERSION
-    # to version $2.  Undo the effects of "prerm upgrade $2".
-    :
 
+    abort-upgrade|abort-remove|abort-deconfigure)
     ;;
-  abort-remove)
-    if test "$2" != in-favour; then
-      echo "$0: undocumented call to \`postinst $*'" 1>&2
-      exit 0
-    fi
-    # Back out of an attempt to remove this package, which was due to
-    # a conflict with package $3 (version $4).  Undo the effects of
-    # "prerm remove in-favour $3 $4".
-    :
 
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
     ;;
-  abort-deconfigure)
-    if test "$2" != in-favour -o "$5" != removing; then
-      echo "$0: undocumented call to \`postinst $*'" 1>&2
-      exit 0
-    fi
-    # Back out of an attempt to deconfigure this package, which was
-    # due to package $6 (version $7) which we depend on being removed
-    # to make way for package $3 (version $4).  Undo the effects of
-    # "prerm deconfigure in-favour $3 $4 removing $6 $7".
-    :
-
-    ;;
-  *) echo "$0: didn't understand being called with \`$1'" 1>&2
-     exit 0;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
+
 #DEBHELPER#
 
 exit 0
-
